# Generated by Django 2.2.3 on 2020-06-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('small_description', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('leh ladakh', 'leh ladakh'), ('Meghalaya', 'Meghalaya'), ('Sikkim', 'Sikkim'), ('Goa', 'Goa'), ('Rajasthan', 'Rajasthan'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka')], max_length=30)),
                ('full_description', models.CharField(max_length=150)),
                ('continue_description', models.CharField(blank=True, max_length=5000)),
                ('mythological', models.CharField(blank=True, max_length=5000)),
                ('destination_covered', models.CharField(blank=True, max_length=200)),
                ('categories', models.CharField(choices=[('ADVENTURE', 'ADVENTURE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('COUPLE', 'COUPLE')], max_length=30)),
                ('duration', models.CharField(choices=[('3', '1 to 3'), ('5', '4 to 5'), ('7', '6 to 7'), ('10', 'more then week')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.CharField(blank=True, max_length=200)),
                ('guide', models.CharField(blank=True, max_length=200)),
                ('meals', models.CharField(blank=True, max_length=200)),
                ('transport', models.CharField(blank=True, max_length=200)),
                ('additional', models.CharField(blank=True, max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationExclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(blank=True, max_length=300)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_heading', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=1000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Destination')),
            ],
        ),
    ]
