# Generated by Django 2.2.3 on 2020-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('Himachal_Pradesh', 'Himachal Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('leh ladakh', 'leh ladakh'), ('Meghalaya', 'Meghalaya'), ('Sikkim', 'Sikkim'), ('Goa', 'Goa'), ('Rajasthan', 'Rajasthan'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka')], max_length=30),
        ),
    ]
