# Generated by Django 2.2.3 on 2020-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200613_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.CharField(choices=[('Categories', (('ADVENTURE', 'ADVENTURE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('COUPLE', 'COUPLE'))), ('Categories2', (('ADVENTURE', 'ADVENTURE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('COUPLE', 'COUPLE')))], max_length=30),
        ),
    ]
