# Generated by Django 2.2.3 on 2020-06-13 09:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200613_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Categories', (('ADVENTURE', 'ADVENTURE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('COUPLE', 'COUPLE'))), ('Categories2', (('ADVENTURE', 'ADVENTURE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('COUPLE', 'COUPLE')))], max_length=30),
        ),
    ]
