# Generated by Django 2.2.3 on 2020-06-21 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200613_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='continue_description',
            new_name='mythologi',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='small_description',
            new_name='tagline',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='mythological',
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.CharField(choices=[('ADVENTURE', 'ADVENTURE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('COUPLE', 'COUPLE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destinationday',
            name='day',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='img',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
    ]
