# Generated by Django 2.2.3 on 2020-04-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200403_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snipeet',
            new_name='Snippet',
        ),
    ]
