# Generated by Django 2.2.3 on 2020-05-02 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='body',
        ),
        migrations.AddField(
            model_name='snippet',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='thought',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
