# Generated by Django 2.2.3 on 2020-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200502_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
