# Generated by Django 2.2.3 on 2019-11-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('night', models.IntegerField()),
                ('detail', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Home_background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_large', models.CharField(max_length=15)),
                ('text_small', models.CharField(max_length=25)),
                ('background_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_view', models.CharField(max_length=500)),
                ('about_location', models.CharField(max_length=500)),
                ('about_destination', models.CharField(max_length=500)),
                ('why_choose_us', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('best_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Special_offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('emergencycontact', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('numberofadult', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
