# Generated by Django 2.2.3 on 2020-03-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
