# Generated by Django 2.2.3 on 2020-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming_destination',
            name='detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
