# Generated by Django 2.2.3 on 2020-03-09 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200309_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming_destination',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcoming_destination',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
