# Generated by Django 2.2.3 on 2020-04-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_delete_destinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popular_destinations',
        ),
    ]
