# Generated by Django 2.2.3 on 2020-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_delete_popular_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('region', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('FAMILY', 'FAMILY'), ('ROMANTIC', 'ROMANTIC')], max_length=30)),
                ('activities', models.CharField(choices=[('ADVENTURE', 'ADVENTURE'), ('WILDLIFE', 'WILDLIFE'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES')], max_length=30)),
                ('duration', models.CharField(choices=[('3', '1 to 3'), ('5', '4 to 5'), ('7', '6 to 7'), ('10', 'more then week')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
