# Generated by Django 2.2.3 on 2020-03-09 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_upcoming_destination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming_destination',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
