# Generated by Django 2.2.3 on 2020-04-29 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thought',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
