# Generated by Django 2.2.3 on 2020-03-09 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_upcoming_destination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular_destinations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular_destinations',
            name='detail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='popular_destinations',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
