# Generated by Django 2.2.3 on 2020-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200429_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='activities',
        ),
        migrations.AlterField(
            model_name='destinations',
            name='categories',
            field=models.CharField(choices=[('ADVENTURE', 'ADVENTURE'), ('WILDLIFE', 'WILDLIFE'), ('SOLO', 'SOLO'), ('GROUP', 'GROUP'), ('RELIGOUS', 'RELIGOUS'), ('WATER_ACTIVITIES', 'WATER_ACTIVITIES'), ('NATURE', 'NATURE'), ('FAMILY', 'FAMILY'), ('ROMANTIC', 'ROMANTIC')], max_length=30),
        ),
    ]
