# Generated by Django 2.2.3 on 2020-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20200309_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming_destination',
            name='type',
            field=models.CharField(choices=[('adva', 'Advan'), ('wild', 'WildLife'), ('frands', 'Widthfrandes'), ('solo', 'solo')], max_length=1),
        ),
    ]
