# Generated by Django 2.2.3 on 2020-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20200309_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming_destination',
            name='type',
        ),
        migrations.AlterField(
            model_name='popular_destinations',
            name='type',
            field=models.CharField(choices=[('adva', 'Advan'), ('wild', 'WildLife'), ('frands', 'Widthfrandes'), ('solo', 'solo')], max_length=1),
        ),
    ]
