# Generated by Django 2.2.3 on 2020-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20200309_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popular_destinations',
            name='type',
            field=models.CharField(choices=[('a', 'Advan'), ('w', 'WildLife'), ('f', 'Widthfrandes'), ('s', 'solo')], max_length=30),
        ),
    ]
